### ISSUE TITLE
Parsing error with rst files with testsetup directive

### ISSUE THREAD

**Issue by astrofrog** [adamchainz/blacken-docs#307]
### Python Version

3.11.2

### Package Version

1.16

### Description

When trying to use blacken-docs with the documentation for one of my packages, blacken-docs is encountering a parsing error. A MWE version of the file I am formatting is:

```
Example
=======

.. testsetup::

    >>> import numpy as np
```

Running this through blacken-docs results in:

```
test.rst:4: code block parse error Cannot parse: 1:0: >>> import numpy as np
```

**Comment by adamchainz** [comment]
According to [the test covering `testsetup`](https://github.com/adamchainz/blacken-docs/blob/cdfa852fea1225f8e68eb38c1d63c1df8cf23e66/tests/test_blacken_docs.py#L311) and [examples on GitHub](https://github.com/search?q=testsetup+language%3AreStructuredText&type=code&repo=&langOverride=&start_value=1&l=reStructuredText), `testsetup` is for Python blocks, not REPL blocks (`>>>`). So I think your usage is incorrect, rather than blacken-docs’ behaviour.

If there’s something I’ve missed, let me know!
